### ISSUE TITLE
HTML Validator: Section heeft geen heading

### ISSUE THREAD

**Issue by Annevd** [zainablfz/the-startup-responsive-interactieve-website#12]
![image](https://github.com/zainablfz/the-startup-responsive-interactieve-website/assets/144004647/8c9e32a6-0506-404d-886c-6674b78fb52f)

De validator verwacht in een section een ten minste een heading.
Om dit op te lossen zou je kunnen kijken of hierin een h2-h6 past. Als dit niet van toepassing is zou je het in een div kunnen veranderen.

Hier kan je nog meer lezen over uitzonderingen als het gaat om sections zonder heading:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#using_a_section_without_a_heading

**Comment by zainablfz** [comment]
Ik heb een `h3` toegevoegd in de section! 
```
 <section class="popup">
        <h3 class="visually-hidden">Modal to subscribe</h3>
```
