### ISSUE TITLE
GRRR logo kleur

### ISSUE THREAD

**Issue by lemuelmgsn** [zainablfz/the-startup-responsive-interactieve-website#5]
![image](https://github.com/zainablfz/the-startup-responsive-interactieve-website/assets/144004180/433a8e13-c9c6-4998-a9b2-2893220f2541)

De font-kleur van de GRRR logo heeft niet voldoende contrast.

**Comment by zainablfz** [comment]
De kleur veranderd! 


![Image](https://github.com/zainablfz/the-startup-responsive-interactieve-website/assets/144009548/fa726471-cd36-4cbc-be74-26144e3a1c14)



![Image](https://github.com/zainablfz/the-startup-responsive-interactieve-website/assets/144009548/e5d7bd9e-5734-465b-b8c7-3bb420e1e137)
